apiVersion: v1
kind: ReplicationController
metadata:
  name: update-demo-kitten
spec:
  selector:
    name: update-demo
    version: kitten
  template:
    metadata:
      labels:
        name: update-demo
        version: kitten
    spec:
      containers:
      - image: registry.cn-hangzhou.aliyuncs.com/serverless-kubernetes/update-demo:nautilus
        name: update-demo
        ports:
        - containerPort: 80
          protocol: TCP
